from datetime import datetime

from typing import Literal

from pydantic import BaseModel, Field


# ==========================================================
# REPORT TYPES
# ==========================================================

ReportType = Literal[
    "LANDSLIDE",
    "ROAD_BLOCKAGE",
    "ROAD_CRACK",
    "SLOPE_CRACK",
    "SLOPE_MOVEMENT",
    "ROCKFALL",
    "FLOODING",
    "OTHER",
]


# ==========================================================
# CREATE REPORT
# ==========================================================

class ReportCreate(BaseModel):

    report_type: ReportType = "OTHER"

    description: str = Field(
        default="",
        max_length=2000,
    )

    latitude: float = Field(
        ge=-90,
        le=90,
    )

    longitude: float = Field(
        ge=-180,
        le=180,
    )

    # Client-side timestamp.
    # Useful when reports are created offline.
    reported_at: datetime | None = None


# ==========================================================
# OFFLINE REPORT SYNCHRONIZATION
# ==========================================================

class OfflineReportSync(BaseModel):

    # Unique ID generated by the client device.
    # Prevents duplicate reports during repeated sync attempts.
    client_report_id: str = Field(
        min_length=8,
        max_length=100,
    )

    report_type: ReportType = "OTHER"

    description: str = Field(
        default="",
        max_length=2000,
    )

    latitude: float = Field(
        ge=-90,
        le=90,
    )

    longitude: float = Field(
        ge=-180,
        le=180,
    )

    severity: Literal[
        "LOW",
        "MODERATE",
        "HIGH",
        "CRITICAL",
    ] = "MODERATE"

    # Original time when the report was created
    # on the offline device.
    offline_created_at: datetime | None = None


# ==========================================================
# VERIFY REPORT
# ==========================================================

class ReportVerify(BaseModel):

    status: Literal[
        "VERIFIED",
        "REJECTED",
    ]

    note: str = Field(
        default="",
        max_length=500,
    )


# ==========================================================
# REPORT OUTPUT
# ==========================================================

class ReportOut(BaseModel):

    id: int

    user_id: int | None = None

    reporter_name: str | None = None

    report_type: str

    description: str

    latitude: float

    longitude: float

    image_url: str | None = None

    video_url: str | None = None

    severity: str = "MODERATE"

    status: str

    # Offline synchronization information.
    client_report_id: str | None = None

    is_offline_report: bool = False

    offline_created_at: datetime | None = None

    synced_at: datetime | None = None

    created_at: datetime

    verified_at: datetime | None = None

    model_config = {
        "from_attributes": True,
    }